In [1]:
import numpy as np

# Basic Array Creation

In [4]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [5]:
arr2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
a = np.array([1,2,3.5,"hello",34])
b = np.array([1,2,3.3,22,1.5])
print(a)
print(b)

['1' '2' '3.5' 'hello' '34']
[ 1.   2.   3.3 22.   1.5]


# Array Generation Function

In [13]:
arr1 = np.zeros(5)
arr2 = np.zeros((3,3))
print(arr1)
print(arr2)

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [14]:
arr1 = np.ones(5)
arr2 = np.ones((5,5))
print(arr1)
print(arr2)

[1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [20]:
arr1 = np.linspace(1,10,5)
print(arr1)

[ 1.    3.25  5.5   7.75 10.  ]


# Random Generation Function

# Array Attributes

# Array Methods

# Reshaping and resizing