In [2]:
import numpy as np

# Basic Array Creation

In [3]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [4]:
arr2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
a = np.array([1,2,3.5,"hello",34])
b = np.array([1,2,3.3,22,1.5])
print(a)
print(b)

['1' '2' '3.5' 'hello' '34']
[ 1.   2.   3.3 22.   1.5]


# Array Generation Function

In [6]:
arr1 = np.zeros(5)
arr2 = np.zeros((3,3))
print(arr1)
print(arr2)

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
arr1 = np.ones(5)
arr2 = np.ones((5,5))
print(arr1)
print(arr2)

[1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [8]:
arr1 = np.linspace(1,10,5)
print(arr1)

[ 1.    3.25  5.5   7.75 10.  ]


# Random Generation Function

In [9]:
np.random.rand(4) #standardization form - Numbers geenarted from (0 to 1)

array([0.13498942, 0.92025125, 0.19050762, 0.5783503 ])

In [10]:
np.random.randn(8) #Normalization form - Numbers generated from (-3 to 3) 

array([ 0.69262024, -0.63864567,  1.99700516,  0.88907708,  1.16850695,
       -0.62490092, -0.07382806, -0.57795275])

In [15]:
np.random.randint(5) # Number generated from 0 to 5

4

In [16]:
np.random.randint(10,50,12) # Numbers generated from 10 to 50 with 12 values 

array([21, 27, 26, 30, 24, 44, 42, 12, 21, 44, 11, 19])

# Array Attributes

In [18]:
# shape - number of rows and number of colums 
arr = np.array([[12,21,23], [1,2,3], [21,3,21]])
arr
arr.shape

(3, 3)

In [19]:
# size - Number of elements in an array
arr.size

9

In [20]:
# dtype - modified or show the type of array 
arr.dtype

dtype('int64')

# Array Methods

In [30]:
arr = np.array([[1,2,3], [12,23,34]])
arr.min()

np.int64(1)

In [31]:
arr.max()

np.int64(34)

In [32]:
arr.sum()

np.int64(75)

In [33]:
np.sum(arr, axis= 0) # axis 0 for colums wise sum

array([13, 25, 37])

In [34]:
np.sum(arr, axis = 1) # axis 1 for row wise sum

array([ 6, 69])

In [35]:
arr.argmax() # max values's index

np.int64(5)

In [36]:
arr.argmin() # min values's index

np.int64(0)

# Reshaping and resizing

In [38]:
arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [41]:
new_arr = arr.reshape(5,4)

In [42]:
new_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [43]:
new_arr.size

20

# Numpy Indexing and slicing of vectors

In [45]:
# slicing - array[start,stop,steps]
arr = np.arange(21,31)
arr

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [48]:
print(arr[4])
print(arr[1:5])

25
[22 23 24 25]


In [53]:
print(arr[3:])
print(arr[:5])
print(arr[1::3])

[24 25 26 27 28 29 30]
[21 22 23 24 25]
[22 25 28]


In [55]:
print(arr[::]) # print whole array 
print(arr[::-1]) # print whole array in reverse order

[21 22 23 24 25 26 27 28 29 30]
[30 29 28 27 26 25 24 23 22 21]


# Numpy Indexing and slicing of Matrix

In [57]:
arr = np.arange(11,31).reshape(4,5)
arr

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [60]:
arr[2,3]
arr[2,0]

np.int64(21)

In [70]:
print(arr[0:2, 1:3])
print(arr[1:, 3:])

[[12 13]
 [17 18]]
[[19 20]
 [24 25]
 [29 30]]


In [81]:
arr[1:,2]

array([18, 23, 28])

# Boolean indexing

In [87]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [88]:
bool_indexing = arr % 2 == 0
bool_indexing

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [89]:
arr = arr[bool_indexing]
arr

array([ 2,  4,  6,  8, 10])