In [3]:
import numpy as np

# Basic Array Creation

In [3]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [4]:
arr2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
a = np.array([1,2,3.5,"hello",34])
b = np.array([1,2,3.3,22,1.5])
print(a)
print(b)

['1' '2' '3.5' 'hello' '34']
[ 1.   2.   3.3 22.   1.5]


# Array Generation Function

In [6]:
arr1 = np.zeros(5)
arr2 = np.zeros((3,3))
print(arr1)
print(arr2)

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
arr1 = np.ones(5)
arr2 = np.ones((5,5))
print(arr1)
print(arr2)

[1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [8]:
arr1 = np.linspace(1,10,5)
print(arr1)

[ 1.    3.25  5.5   7.75 10.  ]


# Random Generation Function

In [9]:
np.random.rand(4) #standardization form - Numbers geenarted from (0 to 1)

array([0.13498942, 0.92025125, 0.19050762, 0.5783503 ])

In [10]:
np.random.randn(8) #Normalization form - Numbers generated from (-3 to 3) 

array([ 0.69262024, -0.63864567,  1.99700516,  0.88907708,  1.16850695,
       -0.62490092, -0.07382806, -0.57795275])

In [15]:
np.random.randint(5) # Number generated from 0 to 5

4

In [16]:
np.random.randint(10,50,12) # Numbers generated from 10 to 50 with 12 values 

array([21, 27, 26, 30, 24, 44, 42, 12, 21, 44, 11, 19])

# Array Attributes

In [4]:
# shape - number of rows and number of colums 
arr = np.array([[12,21,23], [1,2,3], [21,3,21]])
arr
arr.shape

(3, 3)

In [5]:
# size - Number of elements in an array
arr.size

9

In [6]:
# dtype - modified or show the type of array 
arr.dtype

dtype('int64')

In [9]:
# astype - change data type value like int64 -> int32
arr.astype(np.int32)

array([[12, 21, 23],
       [ 1,  2,  3],
       [21,  3, 21]], dtype=int32)

# Array Methods

In [10]:
arr = np.array([[1,2,3], [12,23,34]])
arr.min()

np.int64(1)

In [31]:
arr.max()

np.int64(34)

In [32]:
arr.sum()

np.int64(75)

In [33]:
np.sum(arr, axis= 0) # axis 0 for colums

array([13, 25, 37])

In [34]:
np.sum(arr, axis = 1) # axis 1 for row

array([ 6, 69])

In [35]:
arr.argmax() # max values's index

np.int64(5)

In [36]:
arr.argmin() # min values's index

np.int64(0)

In [15]:
arr.prod() # whole array product 
np.prod(arr,axis=1)

array([   6, 9384])

In [32]:
#mean,mediun/std/var
print(np.mean(arr))
print(np.mean(arr).astype(np.int32))
print(np.median(arr,axis=1))
print(np.std(arr)) # standard deviation
print(np.var(arr)) # variance

12.5
12
[ 2. 23.]
12.284814474246922
150.91666666666666


In [38]:
# # trigonomoetric functions
np.sin(arr)
np.cos(arr)
np.tan(arr)
np.log(arr)

array([[0.        , 0.69314718, 1.09861229],
       [2.48490665, 3.13549422, 3.52636052]])

In [43]:
# dot product - munltiplication of matrices
# rule : (3 X 4) (4 X 3) 1st matrix's column number and 2nd matrix's row number should be same
m1 = np.arange(1,7).reshape((2,3))
m2 = np.arange(1,10).reshape((3,3))
np.dot(m1,m2)

array([[30, 36, 42],
       [66, 81, 96]])

In [53]:
#round/floor/ceil
rn = np.random.random((2,3)) * 100
rn

array([[82.17444328, 72.60086503,  0.99585629],
       [82.06820264, 81.58629281, 24.29422949]])

In [56]:
print(np.round(rn))
print(np.ceil(rn))
print(np.floor(rn))

[[82. 73.  1.]
 [82. 82. 24.]]
[[83. 73.  1.]
 [83. 82. 25.]]
[[82. 72.  0.]
 [82. 81. 24.]]


# Reshaping and resizing

In [38]:
arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [41]:
new_arr = arr.reshape(5,4)

In [42]:
new_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [43]:
new_arr.size

20

# Numpy Indexing and slicing of vectors

In [45]:
# slicing - array[start,stop,steps]
arr = np.arange(21,31)
arr

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [48]:
print(arr[4])
print(arr[1:5])

25
[22 23 24 25]


In [53]:
print(arr[3:])
print(arr[:5])
print(arr[1::3])

[24 25 26 27 28 29 30]
[21 22 23 24 25]
[22 25 28]


In [55]:
print(arr[::]) # print whole array 
print(arr[::-1]) # print whole array in reverse order

[21 22 23 24 25 26 27 28 29 30]
[30 29 28 27 26 25 24 23 22 21]


# Numpy Indexing and slicing of Matrix

In [57]:
arr = np.arange(11,31).reshape(4,5)
arr

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [60]:
arr[2,3]
arr[2,0]

np.int64(21)

In [70]:
print(arr[0:2, 1:3])
print(arr[1:, 3:])

[[12 13]
 [17 18]]
[[19 20]
 [24 25]
 [29 30]]


In [81]:
arr[1:,2]

array([18, 23, 28])

# Boolean indexing

In [93]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [94]:
bool_indexing = arr % 2 == 0
bool_indexing

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [95]:
arr = arr[bool_indexing]
arr

array([ 2,  4,  6,  8, 10])

# Array Operations

**Arithmetic Operations**

In [106]:
arr1 = np.array([1,23,4,3,11,23])
arr2 = np.array([11,32,41,31,21,93])

In [110]:
print(arr1 + arr2) # Addition
print(arr2 - arr1) # Subtraction
print(arr1 * arr2) # Multiplication
print(arr1 / arr2) # Divition
print(arr2 // arr1) # Floor divition
print(arr1 ** arr2) # exponent 

[ 12  55  45  34  32 116]
[10  9 37 28 10 70]
[  11  736  164   93  231 2139]
[0.09090909 0.71875    0.09756098 0.09677419 0.52380952 0.24731183]
[11  1 10 10  1  4]
[                   1 -7483529905152616191                    0
      617673396283947  3105570700629903195 -4211702482426592457]


**Broadcasting**

In [118]:
arr = arr1.reshape(3,2)

In [120]:
arr + 10

array([[11, 33],
       [14, 13],
       [21, 33]])

**Deep and shallow copy**

In [131]:
# Shallow copy - whenever we make any changes on an array but its not reflect the original array
# Deep copy - whenever we make any changes on an array but its reflcet the original array means when we modify the array 
#             then original array also modified

In [154]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([1,2,3,4,5])
sli = arr1[2:]
print(sli)
print(arr1) # arr1 remains same

[3 4 5]
[1 2 3 4 5]


In [155]:
b = arr1.copy() # shallow copy
c = arr2 # deep copy
c[2] = 30
print(b * 10)
print(c + 10)

[10 20 30 40 50]
[11 12 40 14 15]


In [157]:
print(arr1)
print(arr2)

[1 2 3 4 5]
[ 1  2 30  4  5]


**Matrix Opearions**

In [162]:
m1 = np.arange(1,10).reshape(3,3)
m2 = np.arange(11,17).reshape(3,2)

In [165]:
# Matrix multiplication
np.dot(m1,m2)

array([[ 82,  88],
       [199, 214],
       [316, 340]])

In [166]:
# Matrix Transport - row becomes column and column becomes row
m1.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

# Advance Array Manipulation

**Stacking Array**

In [167]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([11,22,33,44,55])

In [168]:
np.vstack((a1,a2)) # vertically arrange the values

array([[ 1,  2,  3,  4,  5],
       [11, 22, 33, 44, 55]])

In [169]:
np.hstack((a1,a2)) # horizontally arrange the values

array([ 1,  2,  3,  4,  5, 11, 22, 33, 44, 55])

In [171]:
np.column_stack((a1,a2)) # column wise arrange the values

array([[ 1, 11],
       [ 2, 22],
       [ 3, 33],
       [ 4, 44],
       [ 5, 55]])

**Splitting Array**

In [183]:
arr = np.arange(1,13).reshape(3,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [184]:
np.hsplit(arr,2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12]])]

In [192]:
vs = np.vsplit(arr,3)
print(vs)

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]
