In [2]:
import numpy as np

# Basic Array Creation

In [3]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [4]:
arr2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
a = np.array([1,2,3.5,"hello",34])
b = np.array([1,2,3.3,22,1.5])
print(a)
print(b)

['1' '2' '3.5' 'hello' '34']
[ 1.   2.   3.3 22.   1.5]


# Array Generation Function

In [6]:
arr1 = np.zeros(5)
arr2 = np.zeros((3,3))
print(arr1)
print(arr2)

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [7]:
arr1 = np.ones(5)
arr2 = np.ones((5,5))
print(arr1)
print(arr2)

[1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [8]:
arr1 = np.linspace(1,10,5)
print(arr1)

[ 1.    3.25  5.5   7.75 10.  ]


# Random Generation Function

In [9]:
np.random.rand(4) #standardization form - Numbers geenarted from (0 to 1)

array([0.13498942, 0.92025125, 0.19050762, 0.5783503 ])

In [10]:
np.random.randn(8) #Normalization form - Numbers generated from (-3 to 3) 

array([ 0.69262024, -0.63864567,  1.99700516,  0.88907708,  1.16850695,
       -0.62490092, -0.07382806, -0.57795275])

In [15]:
np.random.randint(5) # Number generated from 0 to 5

4

In [16]:
np.random.randint(10,50,12) # Numbers generated from 10 to 50 with 12 values 

array([21, 27, 26, 30, 24, 44, 42, 12, 21, 44, 11, 19])

# Array Attributes

In [18]:
# shape - number of rows and number of colums 
arr = np.array([[12,21,23], [1,2,3], [21,3,21]])
arr
arr.shape

(3, 3)

In [19]:
# size - Number of elements in an array
arr.size

9

In [20]:
# dtype - modified or show the type of array 
arr.dtype

dtype('int64')

# Array Methods

# Reshaping and resizing