**Valid Sudoku**

In [2]:
import numpy as np

In [111]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

row_wise = np.sum(s,axis=0)
column_wise = np.sum(s,axis=1)
if np.array_equal(row_wise,column_wise):
    print('Sudoku is valid')
else:
    print('Sudoku is not valid')

Sudoku is valid


**General Questions**

In [157]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [6]:
# Get the shape of the matrix.
data.shape

(5, 3)

In [139]:
# Find the average age of students.
sum_age = data[0:,0].sum()
avg_age = sum_age / 5
print(avg_age)
# Direct mean function
print(np.mean(data[0:,0]))

18.4
18.4


In [20]:
# Extract Math marks of all students.
math_marks = data[0:,1]
print(math_marks)

[85 92 76 65 90]


In [23]:
# Find the highest Science mark.
science_marks = data[0:,2]
print(science_marks.max())

95


In [121]:
# Get details of the student who scored more than 90 in Math.
data[data[:,1] > 90]

array([[19, 92, 88]])

In [122]:
# Increase math marks of all students with 5
data = data[:,1] + 5
data

array([90, 97, 81, 70, 95])

In [127]:
# Find how many students are younger than 19.
age = data[:,0]
bool_age = age < 19
print(len(age[bool_age]))

3


In [138]:
# Calculate the average marks in each subject (column-wise mean).
maths_avg = np.mean(math_marks)
science_avg = np.mean(science_marks)
print(math_avg, science_avg)

81.6 83.2


In [145]:
# Get data of students who scored at least 80 in both subjects.
data[(data[0:,1] >= 80) & (data[0:,2] >= 80)]

array([[19, 92, 88],
       [20, 90, 85]])

In [158]:
# Replace all Science marks < 75 with 0.
data[:,2][data[:,2] < 75] = 0
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])